# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# 自动生成sitemap
Plugins:
- hexo-generator-baidu-sitemap
- hexo-generator-sitemap
sitemap:
  path: sitemap.xml
baidusitemap:
  path: baidusitemap.xml

baidu_url_submit:
  count: 100 # 提交最新的一个链接
  host: 5i1encee.top # 在百度站长平台中注册的域名
  token: Hw38t7Dsp40kSOI6 # 请注意这是您的秘钥，所以请不要把博客源代码发布在公众仓库里!
  path: baidu_urls.txt # 文本文档的地址，新链接会保存在此文本文档里


backup:
    type: git
    theme: fluid
    repository:
       github: git@github.com:5i1encee/5i1encee.github.io.git,Backup
       gitcafe: git@github.com:5i1encee/5i1encee.github.io.git,Backup

########################################以上部分为自添

# Site
title: 5i1encee's Blog #标题
subtitle: Every story has an end, but in life every ending is a new beginning
description: Every story has an end,but in life every ending is a new beginning.   #简介或格言
keywords:
author: 5i1encee   #作者
language: zh-CN   #中文
timezone: Asia/Shanghai  #中国的时区

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: http://5i1encee.top
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
syntax_highlighter: highlight.js
highlight:
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: fluid

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  - type: git
    repository: git@github.com:5i1encee/5i1encee.github.io.git
    branch: main
##同时向百度推送新链接
  - type: 'baidu_url_submitter'